# Generated by Django 5.1.4 on 2024-12-15 17:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "date_of_death",
                    models.DateField(blank=True, null=True, verbose_name="Died"),
                ),
                ("biography", models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите жанр книги", max_length=200, unique=True
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="genre_name_case_insensitive_unique",
                        violation_error_message="Такой жанр уже есть (чувствительно к регистру)",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Введите краткое описание книги", max_length=1000
                    ),
                ),
                ("year", models.DateField(blank=True, null=True)),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                ("book_text", models.TextField()),
                (
                    "popularity",
                    models.SmallIntegerField(
                        help_text="Введите рейтинг популярности от 1 до 10"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.author",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        help_text="Выберите жанр книги", to="main.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["title", "author"],
            },
        ),
    ]
