# Generated by Django 5.1.4 on 2024-12-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to=""
            ),
        ),
    ]
