# Generated by Django 5.1.4 on 2024-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="main/static/image"
            ),
        ),
    ]
