# Generated by Django 5.1.4 on 2024-12-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
    ]
