# Generated by Django 5.1.4 on 2024-12-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_author_biography_alter_author_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="main/static/image",
                verbose_name="Картинка",
            ),
        ),
    ]
