# Generated by Django 5.1.4 on 2024-12-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="biography",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="Биография"
            ),
        ),
    ]
